name: build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - ".gitignore"
      - "**.md"
  push:
    paths-ignore:
      - ".gitignore"
      - "**.md"

jobs:
  build_ohos:
    name: Release for ohos
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup HarmonyOS CLI tools
        uses: ErBWs/setup-ohos@v1
        with:
          version: latest
          cache: true
          run: |
            hvigorw -v
            ohpm --version

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang

      - name: Install project dependencies
        run: |
          ohpm install --all

      - name: Build hap
        run: hvigorw assembleHap -p buildMode=release

      - name: Check build outputs
        run: ls -lat ./ohos/entry/build/default/outputs/default