name: build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - ".gitignore"
      - "**.md"
  push:
    paths-ignore:
      - ".gitignore"
      - "**.md"

jobs:
  build_ohos:
    name: Release for ohos
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup HarmonyOS CLI tools
        uses: ErBWs/setup-ohos@v1
        with:
          version: latest
          cache: true
      - run: hvigorw -v
